declare
Var number;

BEGIN
FOR i IN
(SELECT count(CONTRAT.NUMPOLICE) AS NB,sum(CONTRAT.MONTANT) as ca, ASSURE.NUMASS, MODELE.CODEMODELE, TYPES.CODETYPE, COMPAGNIE.CODECOMP, CONTRAT.DATESOUSCRIPTION
FROM
    ASSURE, CONTRAT, COMPAGNIE ,VEHICULE ,TYPES , MODELE
WHERE
    ASSURE.NUMASS = CONTRAT.NUMASS
AND
    COMPAGNIE.CODECOMP = CONTRAT.CODECOMP
AND
    VEHICULE.MATRICULE = CONTRAT.MATRICULE 
AND 
    TYPES.CODETYPE = VEHICULE.CODETYPE
AND 
    MODELE.CODEMODELE = VEHICULE.CODEMODELE
GROUP BY ASSURE.NUMASS ,MODELE.CODEMODELE, TYPES.CODETYPE, COMPAGNIE.CODECOMP, CONTRAT.DATESOUSCRIPTION) LOOP
    
Var := seq.nextval;
INSERT INTO DTemps VALUES (var, to_char(to_date(i.DATESOUSCRIPTION, 'MM-DD-YYYY'), 'MM'), to_char(to_date(i.DATESOUSCRIPTION, 'MM-DD-YYYY'), 'MONTH'), to_char(to_date(i.DATESOUSCRIPTION, 'MM-DD-YYYY'), 'Q'),to_char(to_date(i.DATESOUSCRIPTION, 'MM-DD-YYYY'), 'YYYY')) ;
INSERT INTO FSOUSCRIPTION VALUES (i.NUMASS,i.CODEMODELE,i.CODETYPE,i.CODECOMP,Var,i.NB,i.ca);
END LOOP ;
COMMIT ;
END ;


select to_char(to_date('11-12-2020','dd-mm-yyyy'),'dd-mm-yyyy')from dual;

