ALTER SYSTEM FLUSH shared_pool;
ALTER SYSTEM FLUSH buffer_cache;

SELECT M.NATIONALITE, SUM(S.CA) as CAN FROM FSOUSCRIPTION S, DMODELE M
    WHERE M.CODEMOD = S.CODEMODELE
    GROUP BY M.NATIONALITE
