ALTER SYSTEM FLUSH shared_pool;
ALTER SYSTEM FLUSH buffer_cache;

SELECT SUM(CA), COUNT(NBCONTRAT) FROM FSOUSCRIPTION
    WHERE FSOUSCRIPTION.CODEMODELE IN 
        (SELECT CODEMOD FROM DMODELE WHERE LIBMOD='YYZPINEZFPCLNMNEOHFTVGRUHPRJQW')
    AND FSOUSCRIPTION.NUMASS IN 
        (SELECT NUMASS FROM DASSURE WHERE NOMVILLE='YEHYCAEJFQZHIZSYNRLXPMNEEQTNTE');

