CREATE MATERIALIZED VIEW VMCAVilleModele
    BUILD IMMEDIATE
    REFRESH COMPLETE ON COMMIT
    ENABLE QUERY REWRITE
    AS 
    SELECT A.CODEVILLE, A.NOMVILLE, M.CODEMOD, M.LIBMOD, S.CA, S.NBCONTRAT
    FROM DASSURE A, DMODELE M, FSOUSCRIPTION S
    WHERE S.NUMASS = A.NUMASS
    AND S.CODEMODELE = M.CODEMOD;