CREATE MATERIALIZED VIEW VMCATRIMESTRIEL
    BUILD IMMEDIATE
    REFRESH COMPLETE ON COMMIT
    ENABLE QUERY REWRITE
    AS
    SELECT T.TRIMESTRE, S.CA
    FROM DTEMPS T, FSOUSCRIPTION S
    WHERE S.CODETEMPS = T.CODETEMPS;