SELECT C.NOMCOMP, M.LIBMARQUE, SUM(S.CA) as CAMC, GROUPING(C.NOMCOMP) as Compagnie, GROUPING(M.LIBMARQUE) as LibelleMarque 
FROM DMODELE M, DCOMPAGNIE C, FSOUSCRIPTION S
WHERE S.CODECOMP = C.CODECOMP
AND S.CODEMODELE = M.CODEMOD
GROUP BY ROLLUP(C.NOMCOMP, M.LIBMARQUE)