SELECT C.NOMCOMP, M.LIBMOD, 
        ,CUME_DIST() OVER (PARTITION BY C.NOMCOMP ORDER BY SUM(S.CA)) AS CUM_DIST_COMP_MODELE
FROM FSOUSCRIPTION S, DCOMPAGNIE C, DMODELE M
WHERE S.CODECOMP = C.CODECOMP
AND S.CODEMODELE = M.CODEMOD
GROUP BY C.NOMCOMP, M.LIBMOD
