SELECT T.MOIS
        ,AVG(SUM(S.CA)) OVER (ORDER BY T.MOIS ROWS 3 PRECEDING) AS MOY_MOBILE_3
FROM FSOUSCRIPTION S, DCOMPAGNIE C, DTEMPS T
WHERE S.CODECOMP = C.CODECOMP
AND S.CODETEMPS = T.CODETEMPS
AND C.CODECOMP = 6
GROUP BY T.MOIS
ORDER BY T.MOIS
